name: Deploy the course using github page

on:
  push:
    branches:
      - main  # Trigger when main branch is pushed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-jupyter nbconvert

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install LaTeX and fonts
        run: |
            sudo apt-get install -y \
              texlive-xetex \
              texlive-fonts-recommended \
              texlive-latex-recommended \
              librsvg2-bin \
              fonts-comfortaa \

      - name: Run Pandoc build
        run: |
          ./build_all_slides.sh
          cp -r ./slides ./docs/slides

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
